require("prototypes.tech")
require("prototypes.item-group")
require("prototypes.controller_pow")
require("prototypes.controller_cpu")
require("prototypes.controller_mem")
require("prototypes.controller_con")
require("prototypes.controller_ext")
require("__programmable-controllers__.prototypes.instructions")
