mode="data"
require("prototypes.tech")
require("prototypes.item-group")
require("prototypes.instructions")
require("prototypes.controller_pow")
require("prototypes.controller_cpu")
require("prototypes.controller_mem")
require("prototypes.controller_con")
require("prototypes.controller_ext")
